#!/bin/sh

set -e
DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
cd $DIR

ANDROID_CORE_CACHE=~/.soomla/cache/android-core
mkdir -p $ANDROID_CORE_CACHE

mkdir -p libs

SQUARE_OTTO_NAME=square-otto-1.3.2.jar
if [ ! -f libs/$SQUARE_OTTO_NAME ];
then
    if [ ! -f $ANDROID_CORE_CACHE/$SQUARE_OTTO_NAME ];
    then
        curl -o $ANDROID_CORE_CACHE/$SQUARE_OTTO_NAME.tmp https://cloud.github.com/downloads/square/otto/square-otto-1.3.2.jar
        mv $ANDROID_CORE_CACHE/$SQUARE_OTTO_NAME.tmp $ANDROID_CORE_CACHE/$SQUARE_OTTO_NAME
    fi
    cp $ANDROID_CORE_CACHE/$SQUARE_OTTO_NAME libs/$SQUARE_OTTO_NAME
fi

KEEVA_NAME=keeva-1.0.1.jar
if [ ! -f libs/$KEEVA_NAME ];
then
    if [ ! -f $ANDROID_CORE_CACHE/$KEEVA_NAME ];
    then
        curl -Lo $ANDROID_CORE_CACHE/$KEEVA_NAME.tmp http://library.soom.la/fetch/keeva-jar/1.0.1?cf=dl_deps
        mv $ANDROID_CORE_CACHE/$KEEVA_NAME.tmp $ANDROID_CORE_CACHE/$KEEVA_NAME
    fi
    cp $ANDROID_CORE_CACHE/$KEEVA_NAME libs/$KEEVA_NAME
fi
