#!/bin/sh

set -e
DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
cd $DIR

if [ ! -d ~/.soomla/cache/android-core ];
then
    mkdir -p ~/.soomla/cache/android-core
fi

if [ ! -d libs ];
then
    mkdir -p libs
fi

if [ ! -f libs/square-otto-1.3.2.jar ];
then
    if [ ! -f ~/.soomla/cache/android-core/square-otto-1.3.2.jar ];
    then
        curl -o ~/.soomla/cache/android-core/square-otto-1.3.2.jar.tmp https://cloud.github.com/downloads/square/otto/square-otto-1.3.2.jar
        mv ~/.soomla/cache/android-core/square-otto-1.3.2.jar.tmp ~/.soomla/cache/android-core/square-otto-1.3.2.jar
    fi
    cp ~/.soomla/cache/android-core/square-otto-1.3.2.jar libs/square-otto-1.3.2.jar
fi